# -*- coding: utf-8 -*-
"""THYhisseLSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bogVqbCc4U5PchmFxBL7eHmu8eZqdTYP
"""

!pip install yfinance

import yfinance as yf
import pandas as pd

data = yf.download("THYAO.IS",
                   start="2016-01-01",
                   end="2026-01-01")

data.head()

data.info()
data.describe()

data.to_csv("THYAO_2016_2025.csv")

from google.colab import files
files.download("THYAO_2016_2025.csv")

if isinstance(data.columns, pd.MultiIndex):
    data.columns = data.columns.get_level_values(0)

data.head()

data = data.reset_index()
data.head()

print("Satır ve sütun sayısı:", data.shape)
print(data.info())

data.isnull().sum()

print("Volume 0 olan gün sayısı:", (data["Volume"] == 0).sum())

data = data[data["Volume"] > 0]
data = data.reset_index(drop=True)

print("Temizlenmiş veri boyutu:", data.shape)

print("Başlangıç tarihi:", data["Date"].min())
print("Bitiş tarihi:", data["Date"].max())

data.describe()

data[["Open", "High", "Low", "Close", "Volume"]].describe()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
plt.plot(data["Date"], data["Close"])
plt.title("THYAO Kapanış Fiyatı (2016-2025)")
plt.xlabel("Tarih")
plt.ylabel("Kapanış Fiyatı")
plt.show()

plt.figure(figsize=(12,6))
plt.plot(data["Date"], data["Volume"])
plt.title("THYAO İşlem Hacmi (2016-2025)")
plt.xlabel("Tarih")
plt.ylabel("İşlem Hacmi")
plt.show()

corr = data[["Open", "High", "Low", "Close", "Volume"]].corr()
corr

import seaborn as sns

plt.figure(figsize=(8,6))
sns.heatmap(corr, annot=True, cmap="coolwarm")
plt.title("Değişkenler Arası Korelasyon Matrisi")
plt.show()

features = ["Open", "High", "Low", "Close", "Volume"]

model_data = data[["Date"] + features].copy()

model_data.head()

dataset = model_data[features].values

print(dataset.shape)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(0, 1))
scaled_data = scaler.fit_transform(dataset)

print(scaled_data[:5])
print(scaled_data.shape)

train_size = int(len(scaled_data) * 0.8)

train_data = scaled_data[:train_size]
test_data = scaled_data[train_size:]

print("Eğitim veri sayısı:", train_data.shape)
print("Test veri sayısı:", test_data.shape)

import numpy as np

def create_multivariate_dataset(dataset, time_step=60, target_col=3):
    X, y = [], []
    for i in range(time_step, len(dataset)):
        X.append(dataset[i-time_step:i, :])
        y.append(dataset[i, target_col])
    return np.array(X), np.array(y)

time_step = 60

X_train, y_train = create_multivariate_dataset(train_data, time_step, target_col=3)
X_test, y_test = create_multivariate_dataset(test_data, time_step, target_col=3)

print("X_train:", X_train.shape)
print("y_train:", y_train.shape)
print("X_test:", X_test.shape)
print("y_test:", y_test.shape)

print("Bir örnek X boyutu:", X_train[0].shape)
print("Bir örnek y değeri:", y_train[0])

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout

model = Sequential()

model.add(LSTM(units=64, return_sequences=True, input_shape=(X_train.shape[1], X_train.shape[2])))
model.add(Dropout(0.2))

model.add(LSTM(units=32, return_sequences=False))
model.add(Dropout(0.2))

model.add(Dense(units=16))
model.add(Dense(units=1))

model.compile(optimizer="adam", loss="mean_squared_error")

model.summary()

history = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=32,
    validation_data=(X_test, y_test),
    verbose=1
)

import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
plt.plot(history.history["loss"], label="Eğitim Kaybı")
plt.plot(history.history["val_loss"], label="Test Kaybı")
plt.title("LSTM Modeli Eğitim ve Test Kayıp Grafiği")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.show()

predictions = model.predict(X_test)

print(predictions.shape)
print(y_test.shape)

def inverse_close_transform(scaled_close_values, scaler, close_index=3, n_features=5):
    dummy = np.zeros((len(scaled_close_values), n_features))
    dummy[:, close_index] = scaled_close_values.reshape(-1)
    inversed = scaler.inverse_transform(dummy)
    return inversed[:, close_index]

predicted_close = inverse_close_transform(predictions, scaler)
actual_close = inverse_close_transform(y_test, scaler)

print(predicted_close[:5])
print(actual_close[:5])

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

mae = mean_absolute_error(actual_close, predicted_close)
mse = mean_squared_error(actual_close, predicted_close)
rmse = np.sqrt(mse)
r2 = r2_score(actual_close, predicted_close)

print("MAE:", mae)
print("MSE:", mse)
print("RMSE:", rmse)
print("R2:", r2)

plt.figure(figsize=(12,6))
plt.plot(actual_close, label="Gerçek Kapanış Fiyatı")
plt.plot(predicted_close, label="Tahmin Edilen Kapanış Fiyatı")
plt.title("THYAO LSTM Gerçek ve Tahmin Kapanış Fiyatları")
plt.xlabel("Test Gözlemi")
plt.ylabel("Kapanış Fiyatı")
plt.legend()
plt.show()

test_dates = model_data["Date"].iloc[train_size + time_step:].reset_index(drop=True)

plt.figure(figsize=(12,6))
plt.plot(test_dates, actual_close, label="Gerçek Kapanış Fiyatı")
plt.plot(test_dates, predicted_close, label="Tahmin Edilen Kapanış Fiyatı")
plt.title("THYAO LSTM Gerçek ve Tahmin Kapanış Fiyatları")
plt.xlabel("Tarih")
plt.ylabel("Kapanış Fiyatı")
plt.legend()
plt.show()

results = pd.DataFrame({
    "Date": test_dates,
    "Gerçek_Close": actual_close,
    "Tahmin_Close": predicted_close,
    "Hata": actual_close - predicted_close
})

results.head()

results.to_csv("THYAO_LSTM_Tahmin_Sonuclari.csv", index=False)

from google.colab import files
files.download("THYAO_LSTM_Tahmin_Sonuclari.csv")

plt.figure(figsize=(10,5))
plt.plot(history.history["loss"], label="Eğitim Kaybı")
plt.plot(history.history["val_loss"], label="Test Kaybı")
plt.title("LSTM Modeli Eğitim ve Test Kayıp Grafiği")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.savefig("loss_grafigi.png", dpi=300, bbox_inches="tight")
plt.show()

plt.figure(figsize=(12,6))
plt.plot(data["Date"], data["Close"])
plt.title("THYAO Kapanış Fiyatı (2016-2025)")
plt.xlabel("Tarih")
plt.ylabel("Kapanış Fiyatı")
plt.savefig("kapanis_fiyati.png", dpi=300, bbox_inches="tight")
plt.show()

plt.figure(figsize=(12,6))
plt.plot(data["Date"], data["Volume"])
plt.title("THYAO İşlem Hacmi (2016-2025)")
plt.xlabel("Tarih")
plt.ylabel("İşlem Hacmi")
plt.savefig("islem_hacmi.png", dpi=300, bbox_inches="tight")
plt.show()

plt.figure(figsize=(12,6))
plt.plot(test_dates, actual_close, label="Gerçek Kapanış Fiyatı")
plt.plot(test_dates, predicted_close, label="Tahmin Edilen Kapanış Fiyatı")
plt.title("THYAO LSTM Gerçek ve Tahmin Kapanış Fiyatları")
plt.xlabel("Tarih")
plt.ylabel("Kapanış Fiyatı")
plt.legend()
plt.savefig("gercek_tahmin.png", dpi=300, bbox_inches="tight")
plt.show()